language: ruby
sudo: required
dist: trusty
group: edge # https://github.com/travis-ci/travis-ci/issues/5448
services:
  - docker
before_install:
  - gem update --system --no-doc # https://github.com/sickill/rainbow/issues/49
install:
  - gem install --no-doc test-kitchen kitchen-docker
script:
  - kitchen test
matrix:
  include:
    - env: KITCHEN_PLATFORM=debian KITCHEN_SCRIPT=2.3
    - env: KITCHEN_PLATFORM=debian KITCHEN_SCRIPT=2.4
    - env: KITCHEN_PLATFORM=debian KITCHEN_SCRIPT=2.5
    - env: KITCHEN_PLATFORM=debian KITCHEN_SCRIPT=2.6
    - env: KITCHEN_PLATFORM=debian KITCHEN_SCRIPT=2.7
    - env: KITCHEN_PLATFORM=debian KITCHEN_SCRIPT=3.0
    - env: KITCHEN_PLATFORM=debian KITCHEN_SCRIPT=stable
    - env: KITCHEN_PLATFORM=centos KITCHEN_SCRIPT=2.3
    - env: KITCHEN_PLATFORM=centos KITCHEN_SCRIPT=2.4
    - env: KITCHEN_PLATFORM=centos KITCHEN_SCRIPT=2.5
    - env: KITCHEN_PLATFORM=centos KITCHEN_SCRIPT=2.6
    - env: KITCHEN_PLATFORM=centos KITCHEN_SCRIPT=2.7
    - env: KITCHEN_PLATFORM=centos KITCHEN_SCRIPT=3.0
    - env: KITCHEN_PLATFORM=centos KITCHEN_SCRIPT=stable
  allow_failures:
    - env: KITCHEN_PLATFORM=debian KITCHEN_SCRIPT=2.3
    - env: KITCHEN_PLATFORM=centos KITCHEN_SCRIPT=2.3
